FROM node:8.12

ARG WEBHOOK_TOKEN
ENV WEBHOOK_TOKEN=$WEBHOOK_TOKEN

ARG BOT_ACCESS_TOKEN
ENV BOT_ACCESS_TOKEN=$BOT_ACCESS_TOKEN

ARG FACEBOOK_APP_SECRET
ENV FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET

COPY . .

RUN npm install

EXPOSE 80

CMD ["node", "server.js"]
